apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production   
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fiawornunobel@gmail.com
    privateKeySecretRef:
      name: bel-crm-account-key
    solvers: 
    - http01:
        ingress:
          class: nginx